jobs:
  build:
    docker: #执行容器
      - image: circleci/node:10 #依赖环境
    branches: #分支
      only:
      - main
    steps:
      - run: 
          name: Install
          command: npm install
      - run: 
          name: Build
          command: npm run build
