version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:14.16.0
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: sudo npm install -g npm@6
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run build
      - run: echo '部署开始'
      - run: sudo apt-get update && sudo apt-get install rsync
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - add_ssh_keys:
          fingerprints:
            - "ca:63:df:7f:17:7e:e8:b3:43:cd:8f:e1:a1:50:e5:76"
      - run: echo yes
      - deploy:
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "main" ]; then
              rsync -avc -e 'ssh -p 2222' build $SSH_USER@$SSH_IP:/home/hanserena/Blog/
            else
              echo "Not main branch"
            fi
      - run: echo '部署完毕'
workflows:
  version: 2
  commit-workflow::
    jobs:
      - build:
          filters:
            branches:
              only: main
