add_ssh_keys: 
  fingerprints: "ca:63:df:7f:17:7e:e8:b3:43:cd:8f:e1:a1:50:e5:76"
jobs:
  build:
    docker: #执行容器
      - image: circleci/node:10 #依赖环境
    branches: #分支
      only:
      - main
    steps:
      - run: 
          name: Install
          command: npm install
      - run: 
          name: Build
          command: npm run build
